name: Bug Report
description: Report a bug, broken or incorrect behavior
labels: ["Bug::Bot"]
title: "[BUG] Enter your title here"

body:
  - type: markdown
    attributes:
      value: >
        Thank you for you time to fill in this bug report. This project is based on people contributing to the 
        repository. If you need support, check out the [Discord server](https://discord.gg/j2PAF9Wru8).

  - type: input
    attributes:
      label: Errors/Exceptions
      description: Which errors or exceptions are raised?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A simple and clear summary of the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduce
      description: Is this bug reproducible? If yes, please give us a step-by-step guide of how to reproduce this.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: A short and clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Traceback
      description: If a traceback is provided, please paste it here.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Bug report checklist
      description: Let's make sure you have properly set up the bug report.
      options:
        - label: I have searched the open issues for duplicates.
          required: true
        - label: I have shown the entire traceback, if possible.
          required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Additional information about the error/bug.